######################################################################
# Automatically generated by qmake (3.1) Mon Apr 8 15:18:27 2024
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += JoystickList.pro
